### PR TITLE
Rubocop fixes

### LINKED ISSUE #178: Improve container testing
We can remove a hack in our test according to https://github.com/dry-rb/dry-container/issues/62

### PR DESCRIPTION
**Pull request by ehannes**
When this is merged, there's another branch that should be reviewed with even more fixes 😄 

Fixes #178

### CODE REVIEW

File: spec/fortnox/api/mappers/contexts/json_conversion.rb [hunk 1]
```diff
@@ -2,53 +2,66 @@
...
+    stub_const('Test::ProductDesignerMapper', Class.new(Test::BaseMapper))
+    stub_const('Test::ProductDesignerMapper::KEY_MAP', { id: 'ID' }.freeze)
 
-      class Category < Fortnox::API::Model::Base
+    stub_const('Test::ProductMapper', Class.new(Test::BaseMapper))
+    stub_const(
+      'Test::ProductMapper::KEY_MAP',
+      {
+        vat: 'VAT',
+        url: '@url' # TODO: How to handle url attribute?
```
Comment (ehannes) [inline spec/fortnox/api/mappers/contexts/json_conversion.rb:24]: Old comment...

File: spec/fortnox/api/models/base_spec.rb [hunk 2]
```diff
@@ -24,35 +24,33 @@
     end
 
     context 'without required attribute' do
-      subject { -> { entity_class.new({}) } }
-
-      it { is_expected.to raise_error Fortnox::API::Exception }
```
Comment (ehannes) [inline spec/fortnox/api/models/base_spec.rb:29]: Removes some unnecessary tests here...

File: spec/fortnox/api/types/housework_types_spec.rb [hunk 3]
```diff
@@ -42,49 +45,46 @@
...
+  it_behaves_like 'housework type', 'GARDENING', 'TYPE_RUT'
+  it_behaves_like 'housework type', 'BABYSITTING', 'TYPE_RUT'
+  it_behaves_like 'housework type', 'OTHERCARE', 'TYPE_RUT'
+  it_behaves_like 'housework type', 'OTHERCOSTS', 'TYPE_RUT', housework: false
 
   # rubocop:disable RSpec/RepeatedExample
   # rubocop:disable RSpec/RepeatedDescription
   pending 'to be added' do
-    raise Exception, 'Will be supported 2021-01-01'
+    raise StandardError, 'Will be supported 2021-01-01'
```
Comment (ehannes) [inline spec/fortnox/api/types/housework_types_spec.rb:79]: Rubocop suggested changing from Exception to StandardError

File: spec/spec_helper.rb [hunk 4]
```diff
@@ -26,19 +26,6 @@
 
   WebMock.disable_net_connect!(allow: 'codeclimate.com')
 
-  config.before do
```
Comment (ehannes) [inline spec/spec_helper.rb:29]: Not needed anymore since we are using stubs instead

File: .rubocop.yml [hunk 5]
```diff
@@ -23,3 +23,15 @@ Metrics/BlockLength:
 Naming/PredicateName:
   Exclude:
     - 'spec/support/matchers/**/*'
+
+Naming/RescuedExceptionsVariableName:
+  PreferredName: exception
```
Comment (d-Pixie) [inline .rubocop.yml:28]: ❤️

File: .rubocop.yml [hunk 6]
```diff
@@ -23,3 +23,15 @@ Metrics/BlockLength:
...
+
+Style/WordArray:
+  EnforcedStyle: brackets
```
Comment (d-Pixie) [inline .rubocop.yml:31]: ❤️

File: lib/fortnox/api/repositories/base.rb [hunk 7]
```diff
@@ -111,7 +111,7 @@ def expired?(token)
           decoded_token = JWT.decode token, nil, false
           decoded_token[0]['exp'] < (Time.now.to_i - TIME_MARGIN_FOR_ACCESS_TOKEN_RENEWAL)
         rescue JWT::DecodeError
-          raise Exception, "Could not decode access token for token store \"#{@token_store_name}\""
+          raise Fortnox::API::Exception, "Could not decode access token for token store \"#{@token_store_name}\""
```
Comment (d-Pixie) [inline lib/fortnox/api/repositories/base.rb:114]: Why do you need this if you have:
```
Lint/RaiseException:
  AllowedImplicitNamespaces: ['Fortnox::API']
```

File: lib/fortnox/api/types/enums.rb [hunk 8]
```diff
@@ -36,16 +36,11 @@ def self.lower_case
...
-          MAJORAPPLIANCEREPAIR MOVINGSERVICES ITSERVICES CLEANING
-          TEXTILECLOTHING SNOWPLOWING GARDENING BABYSITTING OTHERCARE
-          OTHERCOSTS
-        ],
-        legacy_rut: %w[COOKING TUTORING]
+        rot: ['CONSTRUCTION', 'ELECTRICITY', 'GLASSMETALWORK', 'GROUNDDRAINAGEWORK', 'MASONRY', 'PAINTINGWALLPAPERING',
+              'HVAC', 'OTHERCOSTS'],
+        rut: ['MAJORAPPLIANCEREPAIR', 'MOVINGSERVICES', 'ITSERVICES', 'CLEANING', 'TEXTILECLOTHING', 'SNOWPLOWING',
+              'GARDENING', 'BABYSITTING', 'OTHERCARE', 'OTHERCOSTS'],
+        legacy_rut: ['COOKING', 'TUTORING']
```
Comment (d-Pixie) [inline lib/fortnox/api/types/enums.rb:43]:
```suggestion
        rot: [
          'CONSTRUCTION',
          'ELECTRICITY',
          'GLASSMETALWORK',
          'GROUNDDRAINAGEWORK',
          'MASONRY',
          'PAINTINGWALLPAPERING',
          'HVAC',
          'OTHERCOSTS'
        ],
        rut: [
          'MAJORAPPLIANCEREPAIR',
          'MOVINGSERVICES',
          'ITSERVICES',
          'CLEANING',
          'TEXTILECLOTHING',
          'SNOWPLOWING',
          'GARDENING',
          'BABYSITTING',
          'OTHERCARE',
          'OTHERCOSTS'
        ],
        legacy_rut: [
          'COOKING',
          'TUTORING'
        ]
```

File: spec/fortnox/api/repositories/base_spec.rb [hunk 9]
```diff
@@ -221,19 +221,19 @@ def refresh_token=; end
...
+                         ''
+                       end
 
-              def access_token=; end
+                       def access_token=; end
 
-              def refresh_token=; end
-            end.new
+                       def refresh_token=; end
+                     end.new
```
Comment (d-Pixie) [inline spec/fortnox/api/repositories/base_spec.rb:236]: Why not just make it a module and skip the need for `.new`?

File: spec/fortnox/api/types/housework_types_spec.rb [hunk 10]
```diff
@@ -25,7 +28,7 @@
     let(:document) do
       Fortnox::API::Model::Order.new(
         customer_number: '1',
-        tax_reduction_type: tax_reduction_type,
+        tax_reduction_type: Object.const_get(tax_reduction_type),
```
Comment (d-Pixie) [inline spec/fortnox/api/types/housework_types_spec.rb:31]: Hmmm, this looks weird ...

File: spec/fortnox/api/types/housework_types_spec.rb [hunk 11]
```diff
@@ -42,49 +45,46 @@
         let(:error_message) { 'Skattereduktion för den valda typen av husarbete har upphört.' }
 
         it 'raises an error' do
```
Comment (d-Pixie) [inline spec/fortnox/api/types/housework_types_spec.rb:47]: This could quite easily be rewritten to
```
it is_expected.to raise_error(Fortnox::API::RemoteServerError, error_message)
```
since you don't really need the description there ...

File: spec/fortnox/api/types/housework_types_spec.rb (hunk 3 above)
Comment (d-Pixie) [reply spec/fortnox/api/types/housework_types_spec.rb:79]: Do we need this anymore? The "Will be supported" date has passed ...

File: spec/fortnox/api/types/housework_types_spec.rb [hunk 12]
```diff
@@ -42,49 +45,46 @@
...
+    raise StandardError, 'Will be supported 2021-01-01'
     # it_behaves_like 'housework type', 'HOMEMAINTENANCE', TYPE_RUT
     # it_behaves_like 'housework type', 'FURNISHING', TYPE_RUT
     # it_behaves_like 'housework type', 'TRANSPORTATIONSERVICES', TYPE_RUT
     # it_behaves_like 'housework type', 'WASHINGANDCAREOFCLOTHING', TYPE_RUT
   end
 
   pending 'to be added' do
-    raise Exception, 'Will be supported 2021-01-01'
+    raise StandardError, 'Will be supported 2021-01-01'
```
Comment (d-Pixie) [inline spec/fortnox/api/types/housework_types_spec.rb:87]: As has this

File: spec/fortnox/api/types/model_spec.rb [hunk 13]
```diff
@@ -42,7 +38,7 @@
       stub_const('User', user_class)
     end
 
-    it { is_expected.not_to raise_error }
+    it { expect { User.new }.not_to raise_error }
```
Comment (d-Pixie) [inline spec/fortnox/api/types/model_spec.rb:41]: Don't love how this reads ...

File: spec/fortnox/api/types/required_spec.rb [hunk 14]
```diff
@@ -15,25 +15,27 @@
     end
 
     it 'raises an error' do
-      is_expected.to raise_error(Dry::Struct::Error, error_message)
+      expect(subject).to raise_error(Dry::Struct::Error, error_message)
```
Comment (d-Pixie) [inline spec/fortnox/api/types/required_spec.rb:18]: Same here about dropping the description and keeping the is_expected form.

Comment (d-Pixie) [reply spec/fortnox/api/types/required_spec.rb:18]: Also, if this can still be on the form where `subject` is expected to raise an error, why couldn't the last one ^?

File: spec/fortnox/api/types/housework_types_spec.rb (hunk 10 above)
Comment (ehannes) [reply spec/fortnox/api/types/housework_types_spec.rb:31]: Does it? I just pass the class as a string and use `Object.const_get` to "constantize" the string. We don't have the `constantize` method from Rails to use here...

File: spec/fortnox/api/types/housework_types_spec.rb (hunk 3 above)
Comment (ehannes) [reply spec/fortnox/api/types/housework_types_spec.rb:79]: Ye, I need to implement it first 😅 Will do in a follow up PR...

File: spec/fortnox/api/types/housework_types_spec.rb (hunk 12 above)
Comment (ehannes) [reply spec/fortnox/api/types/housework_types_spec.rb:87]: Same here

File: spec/fortnox/api/types/model_spec.rb (hunk 13 above)
Comment (ehannes) [reply spec/fortnox/api/types/model_spec.rb:41]: Ye, I agree. Problem is that Rubocop doesn't like when you have a proc as the `subject`. Not sure why though... I thought it was regarded as bad practice, but maybe this is something we should discuss internally.

File: lib/fortnox/api/repositories/base.rb (hunk 7 above)
Comment (ehannes) [reply lib/fortnox/api/repositories/base.rb:114]: We don't. Good catch 👍

Comment (ehannes) [reply lib/fortnox/api/repositories/base.rb]: Unfortunately, I can't get this to work. I have this config:
```
Lint/RaiseException:
  AllowedImplicitNamespaces: ['Fortnox::API']
```
but I still get this error:
```
lib/fortnox/api/repositories/base.rb:114:17: W: [Correctable] Lint/RaiseException: Use StandardError over Exception.
          raise Exception, "Could not decode access token for token store \"#{@token_store_name}\""
                ^^^^^^^^^
```

Maybe Rubocop is not smart enough. In the [documentation](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/RaiseException) they have an example of `Gem::Exception`, but that exception is directly in a module named `Gem`. Here, we have a class named `Fortnox::API::Repository::Base` that uses the `Fortnox::API::Exception` exception. Don't know how to fix it. I will use the fully qualified name for now...

File: spec/fortnox/api/types/housework_types_spec.rb (hunk 10 above)
Comment (ehannes) [reply spec/fortnox/api/types/housework_types_spec.rb:31]: Before, I created variables for `TYPE_ROT` and `TYPE_RUT`. Now I stub them, which I need to do in an RSpec context, which means they are no longer declared when I run `it_behaves_like 'housework type', 'CONSTRUCTION', 'TYPE_ROT'` (`'TYPE_ROT'` is now a string, before it was a class).

File: spec/fortnox/api/types/model_spec.rb (hunk 13 above)
Comment (ehannes) [reply spec/fortnox/api/types/model_spec.rb:41]: This is where we should use `specify` instead of `it`...

File: spec/fortnox/api/types/required_spec.rb (hunk 14 above)
Comment (ehannes) [reply spec/fortnox/api/types/required_spec.rb:18]: We should not have subject raising an error. See https://blog.rubystyle.guide/rspec/2019/07/17/rspec-implicit-block-syntax.html

File: spec/fortnox/api/repositories/base_spec.rb (hunk 9 above)
Comment (ehannes) [reply spec/fortnox/api/repositories/base_spec.rb:236]: Then we would need to stub it to not leak the module between tests. Better to just have it as an anonymous class as it is...
